# KartaPetsPlus Configuration

# The maximum number of pets a player can own at one time.
max-pets-per-player: 1

# The default pet given to a new player. 'none' for no pet.
default-pet: none

# The tick delay for the pet follow task. 20 ticks = 1 second.
follow-task-ticks: 20

# Enable or disable the economy features of the plugin.
enable-economy: true

# Storage settings
storage:
  # The type of storage to use. Options: YAML, SQLITE, MYSQL
  type: YAML
  mysql:
    host: localhost
    port: 3306
    database: petsplus
    username: root
    password: password
  sqlite:
    file: petsplus.db
