name: KartaPetsPlus
version: 1.0.0
main: com.karta.petsplus.PetsPlus
api-version: '1.21'
author: Jules (AI Assistant)
description: A powerful pets plugin.
commands:
  pets:
    description: Main command for KartaPetsPlus.
    usage: /<command> [subcommand]
    permission: petsplus.use
    aliases: [pet]
permissions:
  petsplus.use:
    description: Allows players to use basic pet commands.
    default: true
  petsplus.shop:
    description: Allows players to open the pet shop.
    default: true
  petsplus.admin:
    description: Allows access to administrative commands.
    default: op
