name: KartaPetsPlus
version: '${project.version}'
main: com.karta.petsplus.KartaPetsPlus
api-version: '1.21'
authors: [Jules]
description: ${project.description}
commands:
  pets:
    description: Opens the pet management menu.
    usage: /<command>
  petshop:
    description: Opens the pet shop menu.
    usage: /<command>
permissions:
  kartapetsplus.use:
    description: Allows players to use pets.
    default: true
  kartapetsplus.shop:
    description: Allows players to use the pet shop.
    default: true
  kartapetsplus.admin:
    description: Admin permissions for reload and management.
    default: op
